# Authors: Yash Patel
# Added the implementation of the neural branch predictors to the gem5
# compiler script

Import('*')

if env['TARGET_ISA'] == 'null':
    Return()

SimObject('BranchPredictor.py')

DebugFlag('Indirect')
Source('bpred_unit.cc')
Source('2bit_local.cc')
Source('btb.cc')
Source('indirect.cc')
Source('ras.cc')
Source('tournament.cc')
Source ('bi_mode.cc')
Source('ltage.cc')
Source('always.cc')
Source('neurobranch.cc')
Source('neuropath.cc')
DebugFlag('FreeList')
DebugFlag('Branch')
DebugFlag('LTage')
